<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/MDirMaster.Master" AutoEventWireup="true" CodeBehind="AL_Out.aspx.cs" Inherits="HR_Salaries.Pages.AL_Out.AL_Out" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    
    <asp:Label ID="lblMessage" runat="server" style="font-size:x-large;"></asp:Label>
    <div class="content">
        <div class="container">
            <div class="col-lg-13">
                <div class="sub-content">
                    <div class="list-group">
                        <asp:Panel ID="Panel1" runat="server">


                        <asp:Panel ID="PalChose" runat="server">
                            <div class="row">
                                <div class="col-6 col-md-3" >
                                    <asp:Button ID="ButAdd" runat="server" Text="أضافة" OnClick="ButAdd_OnClick"/>
                                    </div>
                                <div class="col-6 col-md-3" >
                                    <asp:Button ID="ButUpdate" runat="server" Text="تعديل" OnClick="ButUpdate_OnClick"/>
                                    </div>
                                </div>
                            </asp:Panel>



                            <asp:Panel ID="PalUpdate" runat="server" Visible="false">

                                <div class="row">
                              <div class="col-6 col-md-3" ><asp:TextBox ID="txtUpdate" class="form-control" runat="server" ></asp:TextBox></div>
                              <div class="col-6 col-md-3" style="text-align: right;"><asp:Button style="font-size: unset;" ID="btnSerchUpdate" class="btn btn-primary" runat="server" Text="بحث" OnClick="btnSerchUpdate_Click" /> </div>
                              <div class="col-6 col-md-3"> <asp:Label ID="Label9" runat="server" Text="البحث و التعديل في ملف الـAL"></asp:Label> </div>
                              <div class="col-6 col-md-3"> </div>
                         </div>








                                                        <div class="row" style="padding: 0px 0px 0px 0px;">
                            <div class="col-md-1">  
                                    </div>
                              <div class="col-md-10">  
                     <asp:GridView ID="GVUpdate" runat="server" BackColor="White" BorderColor="#CCCCCC"
                     BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                    CssClass="table table-striped table-bordered table-condensed"
                     AutoGenerateColumns="False" AutoGenerateDeleteButton="False"
                     AutoGenerateSelectButton="True" OnSelectedIndexChanged="GVUpdate_PageIndexChanging" AllowSorting="True">
                    <EditRowStyle Wrap="false" />
                    <FooterStyle BackColor="White" ForeColor="#000066"></FooterStyle>
                    <HeaderStyle BackColor="#5f6b89" Font-Bold="True" ForeColor="White"></HeaderStyle>
                    <PagerStyle HorizontalAlign="Left" BackColor="White" ForeColor="#000066"></PagerStyle>
                    <RowStyle ForeColor="#000066"></RowStyle>
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White"></SelectedRowStyle>
                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>
                    <SortedAscendingHeaderStyle BackColor="#007DBB"></SortedAscendingHeaderStyle>
                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>
                    <SortedDescendingHeaderStyle BackColor="#00547E"></SortedDescendingHeaderStyle>
                </asp:GridView>
         </div>
                               <div class="col-md-1">  
                                    </div>
   </div>



                            </asp:Panel>









                            
                 
                        

                          </asp:Panel>
                        <div dir="ltr">
                         <asp:Panel ID="Panel2" runat="server" Visible="false">
                        <div class="row">
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label1" runat="server" Width="100%" Text="RECORD_DATE" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="RECORD_DATE" runat="server" Width="100%"  required TabIndex="1" ></asp:TextBox>
 
                             <cc1:CalendarExtender ID="CalendarExtender1" runat="server" TargetControlID="RECORD_DATE"
                                    Format="yyyy-MM-dd">
                                </cc1:CalendarExtender>

                               

                            </div>
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label3" runat="server"  Text="INSTITUTION_NUMBER" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" Width="100%" ID="INSTITUTION_NUMBER" runat="server" MaxLength="8" Text="00000154" required TabIndex="1"></asp:TextBox>
                            
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label123" runat="server" Width="100%" Text="LAST_NAME" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="LAST_NAME" runat="server" Width="100%" MaxLength="25" required TabIndex="1"></asp:TextBox>
                            </div>


                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label4" runat="server" Width="100%" Text="FIRST_NAME" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="FIRST_NAME" runat="server" Width="100%" MaxLength="15" required TabIndex="1"></asp:TextBox>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label5" runat="server" Width="100%" Text="BIRTH_NAME"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="BIRTH_NAME" runat="server" Width="100%" MaxLength="20" ></asp:TextBox>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label6" runat="server" Width="100%" Text="FATHER_NAME"  ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="FATHER_NAME" runat="server" Width="100%" MaxLength="20" required OnTextChanged="FATHER_NAME_TextChanged" AutoPostBack="true"></asp:TextBox>
                            </div>
                        </div>
                        <div class="row">

                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label7" runat="server" Width="100%" Text="EMBOSS LINE 1" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="EMBOSS_LINE_1" runat="server" Width="100%" MaxLength="26" required TabIndex="1"></asp:TextBox>
                            </div>
                              <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" ID="Label2" runat="server" Width="100%" Text="EMBOSS LINE 2"></asp:Label></div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="EMBOSS_LINE_2" runat="server" Width="100%" MaxLength="26"></asp:TextBox></div>
                        </div>
                        <div class="row">    <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label8" runat="server" Width="100%" Text="EMBOSS LINE 3"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="EMBOSS_LINE_3" runat="server" Width="100%" MaxLength="26"></asp:TextBox>
                            </div>
                        
                           
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label10" runat="server" Width="100%" Text="TITLE" ForeColor="Red"></asp:Label>
                            </div>


                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="TITLE" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1" ></asp:DropDownList>
                            
                            
                            </div>


                        </div>
                        <div class="row">    <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label11" runat="server" Width="100%" Text="MARITAL_STATUS" ForeColor="Red"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="MARITAL_STATUS" runat="server"  AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                            </div>
                         
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label13" runat="server" Width="100%" Text="TEL_PRIVATE" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" Width="100%" ID="TEL_PRIVATE" runat="server"  MaxLength="15" required TabIndex="1"></asp:TextBox>
                            </div>


                        </div>
                        <div class="row">    <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label130" runat="server" Width="100%" Text="TEL_WORK" ForeColor="Red"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="TEL_WORK" runat="server" Width="100%" MaxLength="15" TabIndex="1"></asp:TextBox>
                            </div>
                       
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label14" runat="server" Width="100%" Text="FAX_PRIVATE"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="FAX_PRIVATE" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                       </div>
                        <div class="row">     <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label15" runat="server" Width="100%" Text="FAX_WORK"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="FAX_WORK" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                           

                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label16" runat="server" Width="100%" Text="ID_NUMBER"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="ID_NUMBER" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                           </div>
                        <div class="row">  <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label17" runat="server" Width="100%" Text="PASSPORT_NUMBER"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="PASSPORT_NUMBER" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label18" runat="server" Width="100%" Text="DRIVING_LICENSE"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="DRIVING_LICENSE" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>


                         </div>
                        <div class="row">   <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label19" runat="server" Width="100%" Text="BIRTH_DATE" ForeColor="Red"></asp:Label>
                            </div>
                       
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="BIRTH_DATE" runat="server" Width="100%" required TabIndex="1"></asp:TextBox>
                                <cc1:CalendarExtender ID="CalendarExtender2" runat="server" TargetControlID="BIRTH_DATE"
                                    Format="yyyy-MM-dd">
                                </cc1:CalendarExtender>
                            </div> 
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label20" runat="server" Width="100%" Text="BIRTH_PLACE"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="BIRTH_PLACE" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                         </div>
                        <div class="row">   <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label21" runat="server" Width="100%" Text="CLIENT_COUNTRY" ForeColor="Red"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="CLIENT_COUNTRY" runat="server"  AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                            </div>
                           

                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label213" runat="server" Width="100%" Text="CLIENT_CITY"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="CLIENT_CITY" runat="server" Width="100%" MaxLength="13"></asp:TextBox>
                            </div>

                         </div>
                        <div class="row">    
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label23" runat="server" Width="100%" Text="CLIENT_LANGUAGE" ForeColor="Red"></asp:Label>
                            </div>
                    
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="CLIENT_LANGUAGE" runat="server"  AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                            </div>    
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label24" runat="server"  Text="NATIONALITY" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="NATIONALITY" runat="server"  AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                            </div>
                            </div>

                         
                            
                           
                            

                           









                            <div class="list-group">
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label25" runat="server" Text="EMPLOYMENT_STATUS" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="EMPLOYMENT_STATUS" runat="server" AutoPostBack="false"  CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label26" runat="server" Text="CLIENT_BRANCH" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="CLIENT_BRANCH" runat="server" MaxLength="3" required TabIndex="1" TextMode="Number" OnTextChanged="CLIENT_BRANCH_TextChanged" AutoPostBack="true"></asp:TextBox>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label27" runat="server" Text="VAT_REG_NUMBER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="VAT_REG_NUMBER" runat="server" MaxLength="15"></asp:TextBox>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label28" runat="server" Text="REGISTRATION_NUMBER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="REGISTRATION_NUMBER" runat="server" MaxLength="15"></asp:TextBox>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label29" runat="server" Text="CLIENT_ORGANIZATION"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="CLIENT_ORGANIZATION" runat="server" MaxLength="8"></asp:TextBox>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label30" runat="server" Text="BANK_CLEARING_NUMBER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="BANK_CLEARING_NUMBER" runat="server" MaxLength="8"></asp:TextBox>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label31" runat="server" Text="BANK_TEL_NUMBER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="BANK_TEL_NUMBER" runat="server" MaxLength="15"></asp:TextBox>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label32" runat="server" Text="BANK_REFERECE"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="BANK_REFERECE" runat="server" MaxLength="8"></asp:TextBox>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label33" runat="server" Text="NOTE_TEXT"></asp:Label>
                                </div>

                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="NOTE_TEXT" runat="server" MaxLength="100"></asp:TextBox>
                                </div>


                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label34" runat="server" Text="EMPLOYMENT_POSITION"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="EMPLOYMENT_POSITION" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" ></asp:DropDownList>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label35" runat="server" Text="EMPLOYER_NAME"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="EMPLOYER_NAME" runat="server" MaxLength="35"></asp:TextBox>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label36" runat="server" Text="EMPLOYMENT_DATE"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="EMPLOYMENT_DATE" runat="server"  ></asp:TextBox>
                                    <cc1:CalendarExtender ID="CalendarExtender3" runat="server" TargetControlID="EMPLOYMENT_DATE"
                                    Format="yyyy-MM-dd">
                                </cc1:CalendarExtender>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label37" runat="server" Text="WORKING_SECTOR"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="WORKING_SECTOR" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" ></asp:DropDownList>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label38" runat="server" Text="RISK_GROUP"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="RISK_GROUP" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" ></asp:DropDownList>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label39" runat="server" Text="MOBILE_NO1"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="MOBILE_NO1" runat="server" MaxLength="15"></asp:TextBox>
                                </div>


                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label40" runat="server" Text="MOBILE_NO2" ></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="MOBILE_NO2" runat="server" MaxLength="15"></asp:TextBox>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label41" runat="server" Text="FATHERS_NAME_L2"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="FATHERS_NAME_L2" runat="server" MaxLength="35"></asp:TextBox>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label42" runat="server" Text="CLIENT_NUMBER_RBS"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="CLIENT_NUMBER_RBS" runat="server" MaxLength="20"></asp:TextBox>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label43" runat="server" Text="PARINT_CLIENT_NUMBER_RBS"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="PARINT_CLIENT_NUMBER_RBS" runat="server" MaxLength="20"></asp:TextBox>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label44" runat="server" Text="SETTLEMENT_BANK_NAME"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="SETTLEMENT_BANK_NAME" runat="server" MaxLength="35"></asp:TextBox>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label45" runat="server" Text="SETTLEMENT_BANK_CITY"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="SETTLEMENT_BANK_CITY" runat="server" MaxLength="20"></asp:TextBox>
                                </div>


                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label46" runat="server" Text="BANK_GUARANTEE"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="BANK_GUARANTEE" runat="server" MaxLength="18"></asp:TextBox>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label47" runat="server" Text="SERVICE_CONTRACT_ID" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="SERVICE_CONTRACT_ID" runat="server" MaxLength="3" Text="400" required TabIndex="1"></asp:TextBox>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label48" runat="server" Text="SERVICE_ID"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="SERVICE_ID" runat="server" MaxLength="3"></asp:TextBox>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label49" runat="server" Text="EXTENTION_FLAG"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="EXTENTION_FLAG" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" ></asp:DropDownList>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label50" runat="server" Text="CLIENT_NUMBER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="CLIENT_NUMBER" runat="server" MaxLength="8"></asp:TextBox>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label51" runat="server" Text="CONDITION_SET" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="CONDITION_SET" runat="server" MaxLength="3" Text="001" required TabIndex="1"></asp:TextBox>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label52" runat="server" Text="CLIENT_LIMIT" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="CLIENT_LIMIT" runat="server" MaxLength="18" Text="0" required TabIndex="1"></asp:TextBox>
                                </div>


                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label53" runat="server" Text="LIMIT_CURRENCY" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="LIMIT_CURRENCY" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label54" runat="server" Text="COUNTER_BANK_ACCOUNT" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="COUNTER_BANK_ACCOUNT" runat="server" MaxLength="35" required TextMode="Number" TabIndex="1"></asp:TextBox>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label55" runat="server" Text="DOMICILIATION_COUNTER_BANK_ACCOUNT_"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="DOMICILIATION_COUNTER_BANK_ACCOUNT_" runat="server" MaxLength="16"></asp:TextBox>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label56" runat="server" Text="COUNTER_BANK_ACCT_NAME"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="COUNTER_BANK_ACCT_NAME" runat="server" MaxLength="20"></asp:TextBox>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label57" runat="server" Text="SETTLEMENT_METHOD" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="SETTLEMENT_METHOD" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label58" runat="server" Text="CLIENT_LEVEL" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="CLIENT_LEVEL" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label59" runat="server" Text="BILLING_LEVEL" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="BILLING_LEVEL" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label60" runat="server" Text="PARENT_APPL_NUMBER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="PARENT_APPL_NUMBER" runat="server" MaxLength="10"></asp:TextBox>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label61" runat="server" Text="CONTRACT_REFERENCE" ForeColor="red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="CONTRACT_REFERENCE" runat="server" MaxLength="8" required TabIndex="1"></asp:TextBox>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label62" runat="server" Text="INSTITUTION_ACC_OFFICER" ForeColor="red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="INSTITUTION_ACC_OFFICER" runat="server" MaxLength="3" Text="001" required TabIndex="1"></asp:TextBox>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label63" runat="server" Text="PROVIDER_ACCT_OFFICER" ForeColor="red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="PROVIDER_ACCT_OFFICER" runat="server" MaxLength="3" TextMode="Number" Text="002" required TabIndex="1"></asp:TextBox>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label64" runat="server" Text="CARD_NUMBER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="CARD_NUMBER" runat="server" TextMode="Number" MaxLength="19"></asp:TextBox>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label65" runat="server" Text="EXPIRY_DATE"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="EXPIRY_DATE" runat="server" ></asp:TextBox>
                                    <cc1:CalendarExtender ID="CalendarExtender4" runat="server" TargetControlID="EXPIRY_DATE"
                                    Format="yyyy-MM-dd">
                                </cc1:CalendarExtender>
                                </div>

                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label66" runat="server" Text="MOTHERS_MAIDEN_NAME"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                  <asp:TextBox CssClass="txt" Width="100%" ID="MOTHERS_MAIDEN_NAME" runat="server" MaxLength="25"></asp:TextBox>
                                </div>

                            </div>

                        


                        <div class="row">
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label67" runat="server" Text="RESIDENCE_STATUS" ForeColor="Red"></asp:Label></div>
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="RESIDENCE_STATUS" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList></div>
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label68" runat="server" Text="COMPANY_NAME"></asp:Label></div>
                            <div class="col-6 col-md-3">
                              <asp:TextBox CssClass="txt" Width="100%" ID="COMPANY_NAME" runat="server" MaxLength="35"></asp:TextBox></div>
                          </div>

                        <div class="row">   <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label69" runat="server" Text="TIME_WITH_PRESENT_EMPLOYER"></asp:Label></div>
                            <div class="col-6 col-md-3">
                              <asp:TextBox CssClass="txt" Width="100%" ID="TIME_WITH_PRESENT_EMPLOYER" runat="server" MaxLength="3"></asp:TextBox></div>
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label70" runat="server" Text="INCOME"></asp:Label></div>
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="INCOME" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" ></asp:DropDownList></div>
                       
                          </div>





                            <div class="row">   <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label71" runat="server" Text="Bank Contact name"></asp:Label></div>
                            <div class="col-6 col-md-3">
                              <asp:TextBox CssClass="txt" Width="100%" ID="Bank_Contact_Name" runat="server" MaxLength="3"></asp:TextBox></div>
                            <div class="col-6 col-md-3">
                            <div class="col-6 col-md-3">
                       
                          </div>
                          </div>
                          </div>

                                <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label12" runat="server" Text="DATE_OF_APP"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="DATE_OF_APPLICATION" runat="server" Width="100%" ></asp:TextBox>
                                    <cc1:CalendarExtender ID="CalendarExtender5" runat="server" TargetControlID="DATE_OF_APPLICATION"
                                    Format="yyyy-MM-dd">
                                </cc1:CalendarExtender>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label72" runat="server" Text="SECURE_REG_IND"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="SECURE_REGISTRATION_INDICATOT" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%"></asp:DropDownList>
                                </div>
                                    </div>



                                <div class="row">
							
							            <div class="col-6 col-md-3">
                                            <asp:Label CssClass="lbl" Width="100%" ID="Label73" runat="server" Text="CMO_REG_IND"></asp:Label>
                                        </div>
                                        <div class="col-6 col-md-3">
                                            <asp:DropDownList ID="CMO_REGISTRATION_INDICATOR" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%"></asp:DropDownList>
                                        </div>
							
                                        <div class="col-6 col-md-3">
                                            <asp:Label CssClass="lbl" Width="100%" ID="Label74" runat="server" Text="CMO_MOBILE_NUM"></asp:Label>
                                        </div>
                                        <div class="col-6 col-md-3">
                                            <asp:TextBox CssClass="txt" ID="CMO_MOBILE_NUMBER" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                                        </div>
								</div>



                                <div class="row">

                                    <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label75" runat="server" Text="COM_STIKER_REG _INDSSSSS"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="COM_STIKER_REGISTRATION_INDICATRO" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%"></asp:DropDownList>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label76" runat="server" Text="IBAN_NUMBER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="IBAN_NUMBER" runat="server" Width="100%" MaxLength="35"></asp:TextBox>
                                </div>

</div>



                                    <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label77" runat="server" Text="STICKER_CARD"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="STICKER_CARD" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%"></asp:DropDownList>
                                </div>
								
								
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label78" runat="server" Text="DELIVERY_METHOD" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:DropDownList ID="DELIVERY_METHOD" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>
                                </div>
                                        </div>


                                    <div class="row">
							
							
							
							     <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label79" runat="server" Text="ADDR_LINE_1" ForeColor="Red" ></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="ADDR_LINE_1" runat="server" Width="100%" MaxLength="35" required TabIndex="1"></asp:TextBox>
                                </div>
							
							
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label80" runat="server" Text="ADDR_LINE_2"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="ADDR_LINE_2" runat="server" Width="100%" MaxLength="35" ></asp:TextBox>
                                </div>
							</div>




                           <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label81" runat="server" Text="Institution"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <!--<asp:TextBox CssClass="txt" ID="ADDR_LINE_3" runat="server" Width="100%" MaxLength="35"></asp:TextBox>-->
                                    <asp:DropDownList ID="ADDR_LINE_33" runat="server" AutoPostBack="false" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="1"></asp:DropDownList>

                                </div>
								
								
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label82" runat="server" Text="STATE"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="STATE" runat="server" Width="100%" MaxLength="35"></asp:TextBox>
                                </div>
								
								
                            </div>



<div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label83" runat="server" Text="OTHER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="OTHER" runat="server" Width="100%" MaxLength="35"></asp:TextBox>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label84" runat="server" Text="POST_CODE"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="POST_CODE" runat="server" Width="100%" MaxLength="20"></asp:TextBox>
                                </div>

    </div>




         <div class="row">
							
							 <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label85" runat="server" Text="ADDRESS_CLIENT_CITY"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="ADDRESS_CLIENT_CITY" runat="server" Width="100%"></asp:TextBox>
                                </div>
								
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label86" runat="server" Text="EMAIL_ADDRESS"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="EMAIL_ADDRESS" runat="server" Width="100%"></asp:TextBox>
                                </div>

             </div>


<div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label87" runat="server" Text="EMAIL_ADDRESS2"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="EMAIL_ADDRESS2" runat="server" Width="100%"></asp:TextBox>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label88" runat="server" Text="ADR1_NAME_OF_CLIE"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="ADR1_NAME_OF_CLIENT" runat="server" Width="100%"></asp:TextBox>
                                </div>
                            </div>



                                    <div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label89" runat="server" Text="ADR 2 STREET 1" ForeColor="Red"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="ADR2STREET1" runat="server" Width="100%"></asp:TextBox>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label90" runat="server" Text="ADR 3 STREET 2"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="ADR3STREET2" runat="server" Width="100%"></asp:TextBox>
                                </div>
                                        </div>



                                    <div class="row">
							
							<div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label91" runat="server" Text="ADR 4 STATE"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="ADR4_STATE" runat="server" Width="100%"></asp:TextBox>
                                </div>
								
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label92" runat="server" Text="ADR5_OTHER"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="ADR5_OTHER" runat="server" Width="100%"></asp:TextBox>
                                </div>
                                        </div>




                           <div class="row">

                                     <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label93" runat="server" Text="POST_CODE1"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="POST_CODE1" runat="server" Width="100%"></asp:TextBox>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label94" runat="server" Text="ADDRESS CLIENT CITY 1"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="ADDRESS_CLIENT_CITY1" runat="server" Width="100%"></asp:TextBox>
                                </div>
                            </div>

<div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label95" runat="server" Text="EMAIL_ADDRESS1"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="EMAIL_ADDRESS1" runat="server" Width="100%"></asp:TextBox>
                                </div>
                                <div class="col-6 col-md-3">
                                </div>
                                <div class="col-6 col-md-3">
                                </div>
    </div>

                               <!-- IBAN & Deduction of advances -->



<div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label22" runat="server" Text="IBAN"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="IBAN" runat="server" Width="100%"></asp:TextBox>
                                </div>
                                <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label96" runat="server" Text="Deduction of advances"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="Deduction_of_advances" runat="server" Width="100%" Text="0"></asp:TextBox>

                                </div>
    </div>


<div class="row">
                                <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" Width="100%" ID="Label97" runat="server" Text="is send?"></asp:Label>
                                </div>
                                <div class="col-6 col-md-3">
                                    <asp:CheckBox ID="isSend" runat="server" />
                                </div>
                                <div class="col-6 col-md-3">
                                </div>
                                <div class="col-6 col-md-3">
                                </div>
    </div>








                                </div>



                            <div class="col-6 col-md-3">
                                <asp:Button style="font-size: unset;" ID="btnSend" runat="server" Text="التالي" width="100%" CssClass="btn btn-success" OnClick="btnSend_Click" />
                                <asp:Button style="font-size: unset;" ID="Button1" runat="server" Text="تجريبي" width="100%" CssClass="btn btn-success" OnClick="Button1_Click" Visible="false" />

                            </div>    
                            <div class="col-6 col-md-3">
                                <asp:Label ID="lblempid" runat="server" Text=""></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:Label ID="AddUpdate" runat="server" Text="Label"></asp:Label><asp:Label ID="CONTRACTREFERENCE" runat="server" Text=""></asp:Label>
                                <asp:Label ID="lbl_id" runat="server" Text=""></asp:Label>
                            </div>
                            </div>
                             </asp:Panel>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
    

    </div>


</asp:Content>

