<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/MDirMaster.Master" AutoEventWireup="true" CodeBehind=" ALForm1.aspx.cs" Inherits="HR_Salaries.Pages.ALForm1" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    
    <asp:Label ID="lblMessage" runat="server"  ></asp:Label>
    <div class="content">
        <div class="container">
            <div class="col-lg-13">
                <div class="sub-content">
                    <div class="list-group">
                        <asp:Panel ID="Panel1" runat="server">


                        <asp:Panel ID="PalChose" runat="server">
                            <div class="row">
                                <div class="col-6 col-md-3" >
                                    <asp:Button ID="ButAdd" runat="server" Text="أضافة" OnClick="ButAdd_OnClick"/>
                                    </div>
                                <div class="col-6 col-md-3" >
                                    <asp:Button ID="ButUpdate" runat="server" Text="تعديل" OnClick="ButUpdate_OnClick"/>
                                    </div>
                                </div>
                            </asp:Panel>



                            <asp:Panel ID="PalUpdate" runat="server" Visible="false">

                                <div class="row">
                              <div class="col-6 col-md-3" ><asp:TextBox ID="txtUpdate" class="form-control" runat="server" ></asp:TextBox></div>
                              <div class="col-6 col-md-3" style="text-align: right;"><asp:Button style="font-size: unset;" ID="btnSerchUpdate" class="btn btn-primary" runat="server" Text="بحث" OnClick="btnSerchUpdate_Click" /> </div>
                              <div class="col-6 col-md-3"> <asp:Label ID="Label9" runat="server" Text="البحث و التعديل في ملف الـAL"></asp:Label> </div>
                              <div class="col-6 col-md-3"> </div>
                         </div>








                                                        <div class="row" style="padding: 0px 0px 0px 0px;">
                            <div class="col-md-1">  
                                    </div>
                              <div class="col-md-10">  
                     <asp:GridView ID="GVUpdate" runat="server" BackColor="White" BorderColor="#CCCCCC"
                     BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                    CssClass="table table-striped table-bordered table-condensed"
                     AutoGenerateColumns="False" AutoGenerateDeleteButton="False"
                     AutoGenerateSelectButton="True" OnSelectedIndexChanged="GVUpdate_PageIndexChanging" AllowSorting="True">
                    <EditRowStyle Wrap="false" />
                    <FooterStyle BackColor="White" ForeColor="#000066"></FooterStyle>
                    <HeaderStyle BackColor="#5f6b89" Font-Bold="True" ForeColor="White"></HeaderStyle>
                    <PagerStyle HorizontalAlign="Left" BackColor="White" ForeColor="#000066"></PagerStyle>
                    <RowStyle ForeColor="#000066"></RowStyle>
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White"></SelectedRowStyle>
                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>
                    <SortedAscendingHeaderStyle BackColor="#007DBB"></SortedAscendingHeaderStyle>
                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>
                    <SortedDescendingHeaderStyle BackColor="#00547E"></SortedDescendingHeaderStyle>
                </asp:GridView>
         </div>
                               <div class="col-md-1">  
                                    </div>
   </div>



                            </asp:Panel>









                            <asp:Panel ID="PalAdd" runat="server" Visible="false">

                            <div class="row">
                              <div class="col-6 col-md-3" ><asp:TextBox ID="txtSerch" class="form-control" runat="server" ></asp:TextBox></div>
                              <div class="col-6 col-md-3" style="text-align: right;"><asp:Button style="font-size: unset;" ID="btnSerch" class="btn btn-primary" runat="server" Text="بحث" OnClick="btnSerch_Click" /> </div>
                              <div class="col-6 col-md-3"> <asp:Label ID="Label22" runat="server" Text="البحث في ملف الموظفين و اضافته الى ملف الـAL"></asp:Label> </div>
                              <div class="col-6 col-md-3"> </div>
                         </div>
                                </asp:Panel>
                 
                        <div class="row" style="padding: 0px 0px 0px 0px;">
                            <div class="col-md-1">  
                                    </div>
                              <div class="col-md-10">  
                     <asp:GridView ID="GriSerch" runat="server" BackColor="White" BorderColor="#CCCCCC"
                     BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                    CssClass="table table-striped table-bordered table-condensed"
                     AutoGenerateColumns="False" AutoGenerateDeleteButton="False"
                     AutoGenerateSelectButton="True" OnSelectedIndexChanged="GriSerch_PageIndexChanging" AllowSorting="True">
                    <EditRowStyle Wrap="false" />
                    <FooterStyle BackColor="White" ForeColor="#000066"></FooterStyle>
                    <HeaderStyle BackColor="#5f6b89" Font-Bold="True" ForeColor="White"></HeaderStyle>
                    <PagerStyle HorizontalAlign="Left" BackColor="White" ForeColor="#000066"></PagerStyle>
                    <RowStyle ForeColor="#000066"></RowStyle>
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White"></SelectedRowStyle>
                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>
                    <SortedAscendingHeaderStyle BackColor="#007DBB"></SortedAscendingHeaderStyle>
                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>
                    <SortedDescendingHeaderStyle BackColor="#00547E"></SortedDescendingHeaderStyle>
                </asp:GridView>
         </div>
                               <div class="col-md-1">  
                                    </div>
   </div>

                          </asp:Panel>
                        <div dir="ltr">
                         <asp:Panel ID="Panel2" runat="server" Visible="false">
                        <div class="row">
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label1" runat="server" Width="100%" Text="RECORD_DATE" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="RECORD_DATE" runat="server" Width="100%"  TextMode="Date" required TabIndex="1"></asp:TextBox>
                                 
                             

                                <cc1:CalendarExtender ID="CalendarExtender1" runat="server" TargetControlID="RECORD_DATE"
                                    Format="yyyy-MM-dd">
                                </cc1:CalendarExtender>

                            </div>
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label3" runat="server"  Text="INSTITUTION_NUMBER" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" Width="100%" ID="INSTITUTION_NUMBER" runat="server" MaxLength="8" Text="00000154" required TabIndex="1"></asp:TextBox>
                            
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label123" runat="server" Width="100%" Text="LAST_NAME" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="LAST_NAME" runat="server" Width="100%" MaxLength="25" required TabIndex="2"></asp:TextBox>
                            </div>


                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label4" runat="server" Width="100%" Text="FIRST_NAME" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="FIRST_NAME" runat="server" Width="100%" MaxLength="15" required TabIndex="3"></asp:TextBox>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label5" runat="server" Width="100%" Text="BIRTH_NAME"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="BIRTH_NAME" runat="server" Width="100%" MaxLength="20" ></asp:TextBox>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label6" runat="server" Width="100%" Text="FATHER_NAME"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="FATHER_NAME" runat="server" Width="100%" MaxLength="20" ></asp:TextBox>
                            </div>
                        </div>
                        <div class="row">

                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label7" runat="server" Width="100%" Text="EMBOSS LINE 1" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="EMBOSS_LINE_1" runat="server" Width="100%" MaxLength="26" required TabIndex="4"></asp:TextBox>
                            </div>
                              <div class="col-6 col-md-3">
                                    <asp:Label CssClass="lbl" ID="Label2" runat="server" Width="100%" Text="EMBOSS LINE 2"></asp:Label></div>
                                <div class="col-6 col-md-3">
                                    <asp:TextBox CssClass="txt" ID="EMBOSS_LINE_2" runat="server" Width="100%" MaxLength="26"></asp:TextBox></div>
                        </div>
                        <div class="row">    <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label8" runat="server" Width="100%" Text="EMBOSS LINE 3"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="EMBOSS_LINE_3" runat="server" Width="100%" MaxLength="26"></asp:TextBox>
                            </div>
                        
                           
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label10" runat="server" Width="100%" Text="TITLE" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="TITLE" runat="server" AutoPostBack="True" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="5"></asp:DropDownList>
                            </div>
                        </div>
                        <div class="row">    <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label11" runat="server" Width="100%" Text="MARITAL_STATUS" ForeColor="Red"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="MARITAL_STATUS" runat="server"  AutoPostBack="True" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="6"></asp:DropDownList>
                            </div>
                         
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label13" runat="server" Width="100%" Text="TEL_PRIVATE" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" Width="100%" ID="TEL_PRIVATE" runat="server"  MaxLength="15" required TabIndex="7"></asp:TextBox>
                            </div>


                        </div>
                        <div class="row">    <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label130" runat="server" Width="100%" Text="TEL_WORK" ForeColor="Red"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="TEL_WORK" runat="server" Width="100%" MaxLength="15" TabIndex="8"></asp:TextBox>
                            </div>
                       
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label14" runat="server" Width="100%" Text="FAX_PRIVATE"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="FAX_PRIVATE" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                       </div>
                        <div class="row">     <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label15" runat="server" Width="100%" Text="FAX_WORK"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="FAX_WORK" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                           

                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label16" runat="server" Width="100%" Text="ID_NUMBER"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="ID_NUMBER" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                           </div>
                        <div class="row">  <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label17" runat="server" Width="100%" Text="PASSPORT_NUMBER"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="PASSPORT_NUMBER" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label18" runat="server" Width="100%" Text="DRIVING_LICENSE"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="DRIVING_LICENSE" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>


                         </div>
                        <div class="row">   <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label19" runat="server" Width="100%" Text="BIRTH_DATE" ForeColor="Red"></asp:Label>
                            </div>
                       
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="BIRTH_DATE" runat="server" Width="100%" TextMode="Date" required TabIndex="9"></asp:TextBox>
                            </div> 
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label20" runat="server" Width="100%" Text="BIRTH_PLACE"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="BIRTH_PLACE" runat="server" Width="100%" MaxLength="15"></asp:TextBox>
                            </div>
                         </div>
                        <div class="row">   <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label21" runat="server" Width="100%" Text="CLIENT_COUNTRY" ForeColor="Red"></asp:Label>
                            </div>
                        
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="CLIENT_COUNTRY" runat="server"  AutoPostBack="True" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="9"></asp:DropDownList>
                            </div>
                           

                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label213" runat="server" Width="100%" Text="CLIENT_CITY"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="CLIENT_CITY" runat="server" Width="100%" MaxLength="13"></asp:TextBox>
                            </div>

                         </div>
                        <div class="row">    <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label23" runat="server" Width="100%" Text="CLIENT_LANGUAGE" ForeColor="Red"></asp:Label>
                            </div>
                    
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="CLIENT_LANGUAGE" runat="server"  AutoPostBack="True" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="10"></asp:DropDownList>
                            </div>    
                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" Width="100%" ID="Label24" runat="server"  Text="NATIONALITY" ForeColor="Red"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:DropDownList ID="NATIONALITY" runat="server"  AutoPostBack="True" CssClass="btn btn-secondary dropdown-toggle dropdown-toggle-split" Width="100%" TabIndex="11"></asp:DropDownList>
                            </div>
                            </div>

                        <div class="row">   
                            
                           
                            

                             <div class="row">   <div class="col-6 col-md-3">
                            </div>
                        
                            <div class="col-6 col-md-3">
                            </div>
                           

                            <div class="col-6 col-md-3">
                                <asp:Label CssClass="lbl" ID="Label12" runat="server" Width="100%" Text="CONTRACT REFERENCE"></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:TextBox CssClass="txt" ID="CONTRACT_REFERENCE" runat="server" Width="100%" MaxLength="8"></asp:TextBox>
                            </div>

                         </div>





                            <div class="col-6 col-md-3">
                                <asp:Button style="font-size: unset;" ID="btnSend" runat="server" Text="التالي" width="100%" CssClass="btn btn-success" OnClick="btnSend_Click" />
                            </div>    
                            <div class="col-6 col-md-3">
                                <asp:Label ID="lblempid" runat="server" Text=""></asp:Label>
                            </div>
                            <div class="col-6 col-md-3">
                                <asp:Label ID="AddUpdate" runat="server" Text="Label"></asp:Label><asp:Label ID="CONTRACTREFERENCE" runat="server" Text=""></asp:Label>
                                <asp:Label ID="lbl_id" runat="server" Text=""></asp:Label>
                            </div>
                            </div>
                             </asp:Panel>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
    

    </div>


</asp:Content>

