<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/MDirMaster.Master" AutoEventWireup="true"
     CodeBehind="Emails.aspx.cs" Inherits="HR_Salaries.Pages.Email.Emails" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <asp:Panel ID="pSearch" runat="server" DefaultButton="btnSubmit">
        <div class="row" style="text-align: center">
            <asp:HiddenField ID="hfEmpID" Value="0" runat="server" />
            <asp:HiddenField ID="hfEmpTempID" runat="server" Value="0" />
            <asp:HiddenField ID="hfEmailID" runat="server" Value="0" />
            <asp:Label ID="lblMessage" runat="server" CssClass="Error" Text=""></asp:Label>
            <br />
        </div>
        <div class="row">
            <div class="columnleft">
                <asp:Label ID="Label32" runat="server" Text="الفرع : "></asp:Label>
            </div>
            <div class="columnRight">
                <asp:DropDownList ID="ddlSBranch" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlSBranch_SelectedIndexChanged" CssClass="ddl">
                </asp:DropDownList>
            </div>
            <div class="columnleft">
                <asp:Label ID="Label33" runat="server" Text="القسم : "></asp:Label>
            </div>
            <div class="columnRight">
                <asp:DropDownList ID="ddlSDep" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlSBranch_SelectedIndexChanged" CssClass="ddl">
                </asp:DropDownList>
            </div>
        </div>
        <div class="row">
            <div class="columnleft">
                <asp:Label ID="Label27" runat="server" Text="الاسم الكامل (عربي) : "></asp:Label>
            </div>
            <div class="columnRight">
                <asp:DropDownList ID="ddlNameAR" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlName_SelectedIndexChanged" CssClass="ddl">
                </asp:DropDownList>
            </div>
            <div class="columnleft">
                <asp:Label ID="Label1" runat="server" Text="الاسم الكامل (أنكليزي) : "></asp:Label>
            </div>
            <div class="columnRight">
                <asp:DropDownList ID="ddlNameEN" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlName_SelectedIndexChanged" CssClass="ddlltr">
                </asp:DropDownList>
            </div>
        </div>
        <div class="row">

            <div class="columnleft"></div>
            <div class="columnRight"></div>
            <div class="columnleft"></div>
            <div class="columnRight">
                <asp:Button ID="btnGetInfo" runat="server" Text="جلب المعلومات" CssClass="btn" OnClick="btnGetInfo_Click" />
            </div>
        </div>
        <hr />
    </asp:Panel>

    <asp:Panel ID="pEdit" runat="server" DefaultButton="btnSubmit" Enabled="False" BorderColor="#333333">
        <div class="row">
            <div class="columnleft" style="width: 99.61%" dir="rtl">
                <asp:GridView ID="gvEmails" runat="server" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" CssClass="grid" AutoGenerateColumns="False" AutoGenerateDeleteButton="False" AutoGenerateSelectButton="True" OnSelectedIndexChanging="gvEmails_SelectedIndexChanging">
                    <EditRowStyle Wrap="false" />
                    <FooterStyle BackColor="White" ForeColor="#000066"></FooterStyle>
                    <HeaderStyle BackColor="#00959a" Font-Bold="True" ForeColor="White"></HeaderStyle>
                    <PagerStyle HorizontalAlign="Left" BackColor="White" ForeColor="#000066"></PagerStyle>
                    <RowStyle ForeColor="#000066"></RowStyle>
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White"></SelectedRowStyle>
                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>
                    <SortedAscendingHeaderStyle BackColor="#007DBB"></SortedAscendingHeaderStyle>
                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>
                    <SortedDescendingHeaderStyle BackColor="#00547E"></SortedDescendingHeaderStyle>
                </asp:GridView>
            </div>
        </div>
        <div class="row">
        </div>
        <div class="row">
            <div class="columnleft">
                <asp:Label ID="Label2" runat="server" Text="عنوان البريد الألكتروني :"></asp:Label>
            </div>
            <div class="columnRight">
                <asp:TextBox ID="txtEmail" runat="server" CssClass="txtltr" MaxLength="255"></asp:TextBox>
            </div>
            <div class="columnleft">
                <asp:Label ID="Label34" runat="server" Text="النوع :"></asp:Label>
            </div>
            <div class="columnRight">
                <asp:DropDownList ID="ddlEmailType" runat="server" CssClass="ddl">
                </asp:DropDownList>
            </div>
        </div>
        <div class="row">

            <div class="columnleft">
                <asp:Label ID="Label4" runat="server" Text="تاريخ الأنشاء :"></asp:Label>
            </div>
            <div class="columnRight">
                <asp:TextBox ID="txtCreationDate" runat="server" MaxLength="15" CssClass="txtltr" AutoPostBack="True" OnTextChanged="txtCreationDate_TextChanged"></asp:TextBox>
                <asp:CalendarExtender ID="txtCreationDate_CalendarExtender" runat="server" Enabled="True" TargetControlID="txtCreationDate" PopupPosition="BottomRight" Format="dd/MM/yyyy">
                </asp:CalendarExtender>
            </div>
            <div class="columnleft">
                <asp:Label ID="Label3" runat="server" Text="حجم الصندوق (MB) :"></asp:Label>
            </div>
            <div class="columnRight">
                <asp:TextBox ID="txtMailBoxSize" runat="server" CssClass="txtltr" MaxLength="255"></asp:TextBox>
            </div>
        </div>

        <div class="row">
            <div class="columnleft">
                <asp:Label ID="Label7" runat="server" Text="الاسم الكامل (عربي) : "></asp:Label>
            </div>
            <div class="columnRight">
                <asp:DropDownList ID="ddlNameUpdateAR" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlNameUpdate_SelectedIndexChanged" CssClass="ddl">
                </asp:DropDownList>
            </div>
            <div class="columnleft">
                <asp:Label ID="Label8" runat="server" Text="الاسم الكامل (أنكليزي) : "></asp:Label>
            </div>
            <div class="columnRight">
                <asp:DropDownList ID="ddlNameUpdateEN" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlNameUpdate_SelectedIndexChanged" CssClass="ddlltr">
                </asp:DropDownList>
            </div>
        </div>

        <div class="row">

            <div class="columnleft">
                <asp:Label ID="Label5" runat="server" Text="اخرى :"></asp:Label>
            </div>
            <div class="columnRight">
                <asp:CheckBox ID="chbIsActive" runat="server" Checked="True" Text="فعــــــــــال" />
            </div>
            <div class="columnleft">
            </div>
            <div class="columnRight">
            </div>
        </div>
        <div class="row"></div>
        <div class="row">
            <asp:Button ID="btnSubmit" runat="server" Text="تعديل" CssClass="btn" OnClick="btnSubmit_Click" />
            <asp:Button ID="btnCancel" runat="server" Text="إلغاء" CssClass="btnCancel" OnClick="btnCancel_Click" CausesValidation="False" UseSubmitBehavior="False" />
        </div>
        <div class="row"></div>
    </asp:Panel>

</asp:Content>
