<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/MDirMaster.Master" AutoEventWireup="true" CodeBehind="EmpResign.aspx.cs" Inherits="HR_Salaries.Pages.Employee.EmpResign" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <div class="row" style="text-align: center">
        <asp:Label ID="lblMessage" runat="server" Text="" CssClass="Error"></asp:Label>
    </div>
    <div class="row">
        <div class="columnleft">
            <asp:Label ID="Label24" runat="server" Text="الفرع : "></asp:Label>
        </div>
        <div class="columnRight">
            <asp:DropDownList ID="ddlSBranch" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlSBranch_SelectedIndexChanged" CssClass="ddl">
            </asp:DropDownList>
        </div>
        <div class="columnleft">
            <asp:Label ID="Label26" runat="server" Text="القسم : "></asp:Label>
        </div>
        <div class="columnRight">
            <asp:DropDownList ID="ddlSDep" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlSBranch_SelectedIndexChanged" CssClass="ddl">
            </asp:DropDownList>
        </div>
    </div>
    <div class="row">
        <div class="columnleft">
        </div>
        <div class="columnRight">
        </div>
        <div class="columnleft">
        </div>
        <div class="columnRight">
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="columnleft">
            <asp:Label ID="Label1" runat="server" Text="الموظف : "></asp:Label>
        </div>
        <div class="columnRight">
            <asp:DropDownList ID="ddlEmployee" runat="server" CssClass="ddl" OnSelectedIndexChanged="ddlEmployee_SelectedIndexChanged" AutoPostBack="True">
            </asp:DropDownList>
        </div>
        <div class="columnleft">
            <asp:Label ID="Label2" runat="server" Text="سبب الإيقاف : "></asp:Label>
        </div>
        <div class="columnRight">
            <asp:DropDownList ID="ddlResignReason" runat="server" CssClass="ddl">
            </asp:DropDownList>
        </div>
    </div>
    <div class="row">
        <%-- <div class="columnleft">
            <asp:Label ID="Label3" runat="server" Text="بموجب الأمر الإداري :"></asp:Label>
        </div>
        <div class="columnRight">
            <asp:FileUpload ID="FileUpload1" runat="server" />
        </div>--%>

        <div class="columnleft">
            <asp:Label ID="Label4" runat="server" Text="بحسب الامر الاداري المرقم :"></asp:Label>
        </div>
        <div class="columnRight">
            <asp:TextBox ID="txtOrderNo" runat="server" CssClass="txt"></asp:TextBox>
        </div>
        <div class="columnleft">
            <asp:Label ID="Label6" runat="server" Text="بعنوان :"></asp:Label>
        </div>
        <div class="columnRight">
            <asp:TextBox ID="txtOrderDesc" runat="server" CssClass="txt"></asp:TextBox>
        </div>
    </div>
    <div class="row">
        <div class="columnleft">
            <asp:Label ID="Label5" runat="server" Text="تاريخ الامر :"></asp:Label>
        </div>
        <div class="columnRight">
            <asp:TextBox ID="txtOrderDate" runat="server" CssClass="txt">yyyy/MM/dd</asp:TextBox>
            <asp:CalendarExtender ID="TextBox2_CalendarExtender" runat="server" Enabled="True" TargetControlID="txtOrderDate" Format="yyyy/MM/dd">
            </asp:CalendarExtender>
        </div>
        <div class="columnleft">
            <asp:Label ID="Label27" runat="server" Text="تاريخ الانفكاك :"></asp:Label>
        </div>
        <div class="columnRight">
            <asp:TextBox ID="txtLeaveDate" runat="server" CssClass="txt">yyyy/MM/dd</asp:TextBox>
            <asp:CalendarExtender ID="txtLeaveDate_CalendarExtender" runat="server" Enabled="True" TargetControlID="txtLeaveDate" Format="yyyy/MM/dd">
            </asp:CalendarExtender>
        </div>

    </div>
    <div class="row" style="height: 90px">
        <div class="columnleft">نوع الامر :</div>
        <div class="columnRight" style="text-align: right">
            <asp:CheckBoxList ID="chbType" runat="server">
            </asp:CheckBoxList>
        </div>
        <div class="columnleft">
        </div>
        <div class="columnRight">
        </div>
    </div>
    <div class="row">
        <asp:GridView ID="gvOrders" runat="server" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" CssClass="grid" AutoGenerateColumns="False" AutoGenerateSelectButton="false"  AllowSorting="True" OnPageIndexChanging="gvOrders_PageIndexChanging" AutoGenerateDeleteButton="True" OnRowDeleting="gvOrders_RowDeleting" >
                    <EditRowStyle Wrap="false" />
                    <FooterStyle BackColor="White" ForeColor="#000066"></FooterStyle>
                    <HeaderStyle BackColor="#00959a" Font-Bold="True" ForeColor="White"></HeaderStyle>
                    <PagerStyle HorizontalAlign="Left" BackColor="White" ForeColor="#000066"></PagerStyle>
                    <RowStyle ForeColor="#000066"></RowStyle>
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White"></SelectedRowStyle>
                    <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>
                    <SortedAscendingHeaderStyle BackColor="#007DBB"></SortedAscendingHeaderStyle>
                    <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>
                    <SortedDescendingHeaderStyle BackColor="#00547E"></SortedDescendingHeaderStyle>
                </asp:GridView>

    </div>
    <br />
    <div class="row">
        <asp:Button ID="btnSubmit" runat="server" Text="إضافة" CssClass="btn" OnClick="btnSubmit_Click" />
        <asp:Button ID="btnCancel" runat="server" Text="إلغاء" CssClass="btnCancel" OnClick="btnCancel_Click" />
    </div>
</asp:Content>
