<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/MDirMaster.Master" AutoEventWireup="true" CodeBehind="Delete_Reference.aspx.cs" Inherits="HR_Salaries.Pages.RESPONSE.Delete_Reference" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">

    <asp:Label ID="lblMessage" runat="server" Style="font-size: x-large;"></asp:Label>
    <div class="content">
        <div class="container">
            <div class="col-lg-13">
                <div class="sub-content">
                    <div class="list-group">
                        <asp:Panel ID="Panel1" runat="server">


                            <asp:Panel ID="PalChose" runat="server">
                                <div class="row">
                                    <div class="col-6 col-md-12">
                                        <asp:Label CssClass="lbl" Width="100%" ID="Label4" runat="server" Text="معلومات الضمانات"></asp:Label>
                                    </div>
                                </div>
                            </asp:Panel>

                        </asp:Panel>
                        <div dir="rtl">




                           



                           


                                <!-- Start Search Panel -->

                             
                        </div>
                        <!-- OnClick -->
                        <br />


                         <asp:Panel ID="PanelSearch" runat="server" >
                                 <div class="row">

                                        <div class="col-6 col-md-6">
                                            <asp:TextBox ID="txtUpdate" class="form-control" runat="server" placeholder="أسم المادة"></asp:TextBox>
                                        </div>
                                        <div class="col-6 col-md-6" style="text-align: right;">
                                            <asp:Button Style="font-size: unset;" ID="btnSerchUpdate" class="btn btn-primary" runat="server" Text="بحث" OnClick="btnSerchUpdate_Click" />
                                        
                                        </div>

                                        <div class="col-6 col-md-3"></div>
                                    </div>


                                    <div class="row" style="padding: 0px 0px 0px 0px;">
                                        <!--OnSelectedIndexChanged="GVUpdate_PageIndexChanging"-->
                                        <div class="col-md-12">
                                            <asp:GridView ID="GVUpdate" runat="server" BackColor="White" BorderColor="#CCCCCC"
                                                BorderStyle="None" BorderWidth="1px" CellPadding="3"
                                                CssClass="table table-striped table-bordered table-condensed"
                                                AutoGenerateColumns="False" AutoGenerateDeleteButton="False"
                                                AutoGenerateSelectButton="True" AllowSorting="True" OnSelectedIndexChanged="GVUpdate_SelectedIndexChanged">
                                                <EditRowStyle Wrap="false" />
                                                <FooterStyle BackColor="White" ForeColor="#000066"></FooterStyle>
                                                <HeaderStyle BackColor="#5f6b89" Font-Bold="True" ForeColor="White"></HeaderStyle>
                                                <PagerStyle HorizontalAlign="Left" BackColor="White" ForeColor="#000066"></PagerStyle>
                                                <RowStyle ForeColor="#000066"></RowStyle>
                                                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White"></SelectedRowStyle>
                                                <SortedAscendingCellStyle BackColor="#F1F1F1"></SortedAscendingCellStyle>
                                                <SortedAscendingHeaderStyle BackColor="#007DBB"></SortedAscendingHeaderStyle>
                                                <SortedDescendingCellStyle BackColor="#CAC9C9"></SortedDescendingCellStyle>
                                                <SortedDescendingHeaderStyle BackColor="#00547E"></SortedDescendingHeaderStyle>
                                            </asp:GridView>
                                        </div>

                                    </div>

                             </asp:Panel>





                        <asp:Panel ID="Panel_Add_Update" runat="server" Visible="false">

                           


                            </asp:Panel>













                        <asp:Panel ID="Panel3" runat="server" Visible="false">
                            <div class="col-6 col-md-12">
                                <asp:Button Style="font-size: unset;" ID="btnSend" runat="server" Text="حــــذف" Width="100%" CssClass="btn btn-success" OnClick="btnSend_Click"  />
                            </div>
                            <br />

                            <div class="col-6 col-md-12">
                            </div>

                        </asp:Panel>

                        <asp:Panel ID="Panel2" runat="server" Visible="false">
                            <div class="col-6 col-md-3">
                                <asp:Button Style="font-size: unset;" ID="btn_yes" runat="server" Text="نعم" Width="100%" CssClass="btn btn-success" OnClick="btnyes_Click"  />
                            </div>
                             <br />
                            <div class="col-6 col-md-3">
                                <asp:Button Style="font-size: unset;" ID="btn_no" runat="server" Text="لا" Width="100%" CssClass="btn btn-danger" OnClick="btnno_Click"  />
                            </div>
                            <br />

                            <div class="col-6 col-md-12">
                            </div>

                        </asp:Panel>






                        <div class="col-6 col-md-3">
                            <asp:Label ID="AddUpdate" runat="server" Text="Label111" Visible="false"></asp:Label>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>




</asp:Content>
